"use client";

import { useEffect, useState } from 'react';
import { useAuthStore } from '@/store/authStore';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

export default function AffiliatesPage() {
  const { token } = useAuthStore();
  const router = useRouter();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Protect the route
    if (!token) {
      router.push('/account');
    }
  }, [token, router]);

  if (!mounted || !token) return <div className="pt-32 min-h-screen bg-ethoBg"></div>;

  return (
    <main className="pt-32 pb-20 min-h-screen bg-ethoBg">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb Navigation */}
        <nav className="text-sm text-gray-500 mb-8 font-medium">
          <Link href="/account" className="hover:text-haitiBlue transition-colors">Your Account</Link>
          <span className="mx-2">›</span>
          <span className="text-ethoDark">Affiliate Program</span>
        </nav>

        <h1 className="text-4xl font-extrabold text-ethoDark mb-4">EthoHaiti Affiliate Program</h1>
        <p className="text-xl text-gray-600 mb-10">Represent the culture and get paid to do it.</p>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden p-8 sm:p-10">
          
          <div className="prose prose-lg text-gray-600 max-w-none">
            <h2 className="text-2xl font-bold text-ethoDark border-b-2 border-gray-100 pb-4 mb-6">How it Works</h2>
            <p>
              We believe in growing with our community. When you join the EthoHaiti Affiliate Program, you are 
              partnering directly with us to spread awareness of premium, culture-driven apparel. 
            </p>
            <p className="mt-4">
              You will receive a unique, trackable link. Every time someone clicks your link and makes a purchase on 
              EthoHaiti, you earn a commission on the sale. It's that simple.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 my-10">
              <div className="text-center">
                <div className="bg-red-50 text-haitiRed w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 font-black text-2xl">1</div>
                <h3 className="font-bold text-ethoDark mb-2">Sign Up</h3>
                <p className="text-sm">Apply to become an affiliate partner using the email below.</p>
              </div>
              <div className="text-center">
                <div className="bg-red-50 text-haitiRed w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 font-black text-2xl">2</div>
                <h3 className="font-bold text-ethoDark mb-2">Share Your Link</h3>
                <p className="text-sm">Post your unique link on Instagram, TikTok, or send it directly to friends.</p>
              </div>
              <div className="text-center">
                <div className="bg-red-50 text-haitiRed w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 font-black text-2xl">3</div>
                <h3 className="font-bold text-ethoDark mb-2">Get Paid</h3>
                <p className="text-sm">Earn cash commissions for every successful order placed through your link.</p>
              </div>
            </div>

            <h2 className="text-2xl font-bold text-ethoDark border-b-2 border-gray-100 pb-4 mb-6 mt-12">Program Rules</h2>
            <ul className="list-disc pl-6 space-y-3 mt-4">
              <li>Commissions are paid out automatically on a monthly basis.</li>
              <li>You cannot earn commissions on your own personal purchases.</li>
              <li>Payouts are subject to a standard 30-day clearing period to account for potential customer returns.</li>
              <li>Affiliates must represent the brand respectfully online.</li>
            </ul>

            <div className="mt-12 bg-gray-50 border border-gray-200 p-8 rounded-lg text-center">
              <h3 className="text-xl font-bold text-ethoDark mb-3">Ready to Join?</h3>
              <p className="text-sm text-gray-500 mb-6">
                Our automated affiliate dashboard is currently under construction. To apply early and get your link manually generated by our team, please email us directly!
              </p>
              <a 
                href="mailto:affiliates@ethohaiti.com?subject=Affiliate Program Application" 
                className="inline-block bg-haitiRed hover:bg-red-700 text-white font-extrabold py-3 px-8 rounded shadow-md transition-colors"
              >
                Apply via Email
              </a>
            </div>
            
          </div>
        </div>

      </div>
    </main>
  );
}